// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function ApproveDecisionByCIO(arg1) {
  return window['go']['main']['App']['ApproveDecisionByCIO'](arg1);
}

export function ApprovePlan(arg1, arg2) {
  return window['go']['main']['App']['ApprovePlan'](arg1, arg2);
}

export function ApproveStock(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ApproveStock'](arg1, arg2, arg3, arg4, arg5);
}

export function ApproveWorkflow(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ApproveWorkflow'](arg1, arg2, arg3, arg4, arg5);
}

export function BatchApproveStocks(arg1, arg2, arg3) {
  return window['go']['main']['App']['BatchApproveStocks'](arg1, arg2, arg3);
}

export function BatchRejectStocks(arg1, arg2, arg3) {
  return window['go']['main']['App']['BatchRejectStocks'](arg1, arg2, arg3);
}

export function BuyFromTradeablePool(arg1, arg2) {
  return window['go']['main']['App']['BuyFromTradeablePool'](arg1, arg2);
}

export function CIOReviewPendingPlans() {
  return window['go']['main']['App']['CIOReviewPendingPlans']();
}

export function CIOReviewPlan(arg1) {
  return window['go']['main']['App']['CIOReviewPlan'](arg1);
}

export function CalculateStructureRisk(arg1) {
  return window['go']['main']['App']['CalculateStructureRisk'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckLLMConnectivity() {
  return window['go']['main']['App']['CheckLLMConnectivity']();
}

export function CleanupOldData() {
  return window['go']['main']['App']['CleanupOldData']();
}

export function ClearAgentTaskLogs(arg1) {
  return window['go']['main']['App']['ClearAgentTaskLogs'](arg1);
}

export function ConfirmTradeApproval(arg1, arg2) {
  return window['go']['main']['App']['ConfirmTradeApproval'](arg1, arg2);
}

export function ConnectNativeTDX() {
  return window['go']['main']['App']['ConnectNativeTDX']();
}

export function CreateInvestmentDecision(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateInvestmentDecision'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateStrategy(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['CreateStrategy'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function DeleteBacktestResult(arg1) {
  return window['go']['main']['App']['DeleteBacktestResult'](arg1);
}

export function DeleteStrategy(arg1) {
  return window['go']['main']['App']['DeleteStrategy'](arg1);
}

export function DeleteTradeableStock(arg1) {
  return window['go']['main']['App']['DeleteTradeableStock'](arg1);
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function EmergencyStop() {
  return window['go']['main']['App']['EmergencyStop']();
}

export function ExecuteAllTasksManually() {
  return window['go']['main']['App']['ExecuteAllTasksManually']();
}

export function ExecuteDailyWorkflow() {
  return window['go']['main']['App']['ExecuteDailyWorkflow']();
}

export function ExecuteManualTrade(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExecuteManualTrade'](arg1, arg2, arg3, arg4, arg5);
}

export function ExecutePhaseManually(arg1) {
  return window['go']['main']['App']['ExecutePhaseManually'](arg1);
}

export function ExecuteTaskManually(arg1) {
  return window['go']['main']['App']['ExecuteTaskManually'](arg1);
}

export function ExecuteWorkflow(arg1) {
  return window['go']['main']['App']['ExecuteWorkflow'](arg1);
}

export function FlushAuditLogs() {
  return window['go']['main']['App']['FlushAuditLogs']();
}

export function ForceAuditCleanup() {
  return window['go']['main']['App']['ForceAuditCleanup']();
}

export function GenerateDailyReview() {
  return window['go']['main']['App']['GenerateDailyReview']();
}

export function GenerateFactorHealthReport() {
  return window['go']['main']['App']['GenerateFactorHealthReport']();
}

export function GenerateMonthlyReport(arg1, arg2) {
  return window['go']['main']['App']['GenerateMonthlyReport'](arg1, arg2);
}

export function GeneratePlan() {
  return window['go']['main']['App']['GeneratePlan']();
}

export function GeneratePlanStockPool() {
  return window['go']['main']['App']['GeneratePlanStockPool']();
}

export function GetAIStatus() {
  return window['go']['main']['App']['GetAIStatus']();
}

export function GetActiveConversation() {
  return window['go']['main']['App']['GetActiveConversation']();
}

export function GetActiveWorkflows() {
  return window['go']['main']['App']['GetActiveWorkflows']();
}

export function GetAgentPermissions(arg1) {
  return window['go']['main']['App']['GetAgentPermissions'](arg1);
}

export function GetAgentTaskLogs(arg1, arg2) {
  return window['go']['main']['App']['GetAgentTaskLogs'](arg1, arg2);
}

export function GetAgentTaskLogsByDays(arg1) {
  return window['go']['main']['App']['GetAgentTaskLogsByDays'](arg1);
}

export function GetAgentTasks(arg1) {
  return window['go']['main']['App']['GetAgentTasks'](arg1);
}

export function GetAgentWorkDetails() {
  return window['go']['main']['App']['GetAgentWorkDetails']();
}

export function GetAgentWorkbench(arg1) {
  return window['go']['main']['App']['GetAgentWorkbench'](arg1);
}

export function GetAllAgentTasks() {
  return window['go']['main']['App']['GetAllAgentTasks']();
}

export function GetAllAgentWorkbenches() {
  return window['go']['main']['App']['GetAllAgentWorkbenches']();
}

export function GetAnnouncements(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAnnouncements'](arg1, arg2, arg3);
}

export function GetApprovedStocks() {
  return window['go']['main']['App']['GetApprovedStocks']();
}

export function GetAuditEventTypes() {
  return window['go']['main']['App']['GetAuditEventTypes']();
}

export function GetAuditLogs(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetAuditLogs'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetAuditRetentionDays() {
  return window['go']['main']['App']['GetAuditRetentionDays']();
}

export function GetAuditServiceStats() {
  return window['go']['main']['App']['GetAuditServiceStats']();
}

export function GetAutoSchedulerStatus() {
  return window['go']['main']['App']['GetAutoSchedulerStatus']();
}

export function GetBacktestResult(arg1) {
  return window['go']['main']['App']['GetBacktestResult'](arg1);
}

export function GetBacktestResults(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetBacktestResults'](arg1, arg2, arg3, arg4);
}

export function GetBacktestStats() {
  return window['go']['main']['App']['GetBacktestStats']();
}

export function GetBoardList(arg1) {
  return window['go']['main']['App']['GetBoardList'](arg1);
}

export function GetBoardStocks(arg1) {
  return window['go']['main']['App']['GetBoardStocks'](arg1);
}

export function GetBuyableStocks() {
  return window['go']['main']['App']['GetBuyableStocks']();
}

export function GetCIOJournal(arg1) {
  return window['go']['main']['App']['GetCIOJournal'](arg1);
}

export function GetCIOStatus() {
  return window['go']['main']['App']['GetCIOStatus']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetContinuousTradingStatus() {
  return window['go']['main']['App']['GetContinuousTradingStatus']();
}

export function GetCurrentCycle() {
  return window['go']['main']['App']['GetCurrentCycle']();
}

export function GetCurrentMarketState() {
  return window['go']['main']['App']['GetCurrentMarketState']();
}

export function GetCurrentPlan() {
  return window['go']['main']['App']['GetCurrentPlan']();
}

export function GetDailyReviews(arg1) {
  return window['go']['main']['App']['GetDailyReviews'](arg1);
}

export function GetDailyStrategyPlans(arg1) {
  return window['go']['main']['App']['GetDailyStrategyPlans'](arg1);
}

export function GetETFMonitorData() {
  return window['go']['main']['App']['GetETFMonitorData']();
}

export function GetETFMonitorKline(arg1) {
  return window['go']['main']['App']['GetETFMonitorKline'](arg1);
}

export function GetFinancialReportAsOf(arg1, arg2) {
  return window['go']['main']['App']['GetFinancialReportAsOf'](arg1, arg2);
}

export function GetFinancialSyncStatus() {
  return window['go']['main']['App']['GetFinancialSyncStatus']();
}

export function GetFundFlow(arg1, arg2) {
  return window['go']['main']['App']['GetFundFlow'](arg1, arg2);
}

export function GetGeneratePlanProgress() {
  return window['go']['main']['App']['GetGeneratePlanProgress']();
}

export function GetIndexSnapshots(arg1) {
  return window['go']['main']['App']['GetIndexSnapshots'](arg1);
}

export function GetLLMCallLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetLLMCallLogs'](arg1, arg2, arg3, arg4);
}

export function GetLLMCallStats(arg1) {
  return window['go']['main']['App']['GetLLMCallStats'](arg1);
}

export function GetLatestAgentTaskLogs() {
  return window['go']['main']['App']['GetLatestAgentTaskLogs']();
}

export function GetLatestDailyReview() {
  return window['go']['main']['App']['GetLatestDailyReview']();
}

export function GetLatestDailyStat() {
  return window['go']['main']['App']['GetLatestDailyStat']();
}

export function GetMarketDataStatus() {
  return window['go']['main']['App']['GetMarketDataStatus']();
}

export function GetMarketIndices() {
  return window['go']['main']['App']['GetMarketIndices']();
}

export function GetMarketPhaseInfo() {
  return window['go']['main']['App']['GetMarketPhaseInfo']();
}

export function GetMarketSixDimReports(arg1) {
  return window['go']['main']['App']['GetMarketSixDimReports'](arg1);
}

export function GetOrchestratorStats() {
  return window['go']['main']['App']['GetOrchestratorStats']();
}

export function GetPendingStocks() {
  return window['go']['main']['App']['GetPendingStocks']();
}

export function GetPendingTradeApprovals() {
  return window['go']['main']['App']['GetPendingTradeApprovals']();
}

export function GetPendingWorkflows() {
  return window['go']['main']['App']['GetPendingWorkflows']();
}

export function GetPlan(arg1) {
  return window['go']['main']['App']['GetPlan'](arg1);
}

export function GetPlannerState() {
  return window['go']['main']['App']['GetPlannerState']();
}

export function GetPlans() {
  return window['go']['main']['App']['GetPlans']();
}

export function GetPolicyStatus() {
  return window['go']['main']['App']['GetPolicyStatus']();
}

export function GetPortfolioNavBenchmark(arg1) {
  return window['go']['main']['App']['GetPortfolioNavBenchmark'](arg1);
}

export function GetPortfolioRiskMetrics() {
  return window['go']['main']['App']['GetPortfolioRiskMetrics']();
}

export function GetPortfolioState() {
  return window['go']['main']['App']['GetPortfolioState']();
}

export function GetPositionSnapshots(arg1, arg2) {
  return window['go']['main']['App']['GetPositionSnapshots'](arg1, arg2);
}

export function GetPositions() {
  return window['go']['main']['App']['GetPositions']();
}

export function GetProfile() {
  return window['go']['main']['App']['GetProfile']();
}

export function GetProfitHistory(arg1) {
  return window['go']['main']['App']['GetProfitHistory'](arg1);
}

export function GetQMTConfig() {
  return window['go']['main']['App']['GetQMTConfig']();
}

export function GetStockSnapshots(arg1) {
  return window['go']['main']['App']['GetStockSnapshots'](arg1);
}

export function GetStockSyncStatus() {
  return window['go']['main']['App']['GetStockSyncStatus']();
}

export function GetStrategies(arg1) {
  return window['go']['main']['App']['GetStrategies'](arg1);
}

export function GetStrategy(arg1) {
  return window['go']['main']['App']['GetStrategy'](arg1);
}

export function GetStrategyList() {
  return window['go']['main']['App']['GetStrategyList']();
}

export function GetSystemHealth() {
  return window['go']['main']['App']['GetSystemHealth']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetSystemStatus() {
  return window['go']['main']['App']['GetSystemStatus']();
}

export function GetTaskSchedulerStatus() {
  return window['go']['main']['App']['GetTaskSchedulerStatus']();
}

export function GetTaskStatus(arg1) {
  return window['go']['main']['App']['GetTaskStatus'](arg1);
}

export function GetTaskStatusByRole() {
  return window['go']['main']['App']['GetTaskStatusByRole']();
}

export function GetTeamActivity(arg1) {
  return window['go']['main']['App']['GetTeamActivity'](arg1);
}

export function GetTierInfo() {
  return window['go']['main']['App']['GetTierInfo']();
}

export function GetTodayTeamActivity() {
  return window['go']['main']['App']['GetTodayTeamActivity']();
}

export function GetTodayTrades() {
  return window['go']['main']['App']['GetTodayTrades']();
}

export function GetTradeHistory(arg1) {
  return window['go']['main']['App']['GetTradeHistory'](arg1);
}

export function GetTradeJSONFiles(arg1) {
  return window['go']['main']['App']['GetTradeJSONFiles'](arg1);
}

export function GetTradeablePoolSummary() {
  return window['go']['main']['App']['GetTradeablePoolSummary']();
}

export function GetTradeableStockLogs(arg1) {
  return window['go']['main']['App']['GetTradeableStockLogs'](arg1);
}

export function GetTradeableStocks(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetTradeableStocks'](arg1, arg2, arg3, arg4, arg5);
}

export function GetTradingMode() {
  return window['go']['main']['App']['GetTradingMode']();
}

export function GetTransparencyData(arg1) {
  return window['go']['main']['App']['GetTransparencyData'](arg1);
}

export function GetTransparencyStats() {
  return window['go']['main']['App']['GetTransparencyStats']();
}

export function GetUpdateStatus() {
  return window['go']['main']['App']['GetUpdateStatus']();
}

export function GetUpgradePath() {
  return window['go']['main']['App']['GetUpgradePath']();
}

export function GetWatchList() {
  return window['go']['main']['App']['GetWatchList']();
}

export function GetWorkflowAgentTasks(arg1) {
  return window['go']['main']['App']['GetWorkflowAgentTasks'](arg1);
}

export function GetWorkflowStats() {
  return window['go']['main']['App']['GetWorkflowStats']();
}

export function GetWorkflowStatus(arg1) {
  return window['go']['main']['App']['GetWorkflowStatus'](arg1);
}

export function GetWorkflowSystemStatus() {
  return window['go']['main']['App']['GetWorkflowSystemStatus']();
}

export function GetWorkflowTaskSummary() {
  return window['go']['main']['App']['GetWorkflowTaskSummary']();
}

export function GetWorkflowTeamMembers() {
  return window['go']['main']['App']['GetWorkflowTeamMembers']();
}

export function GetWorkflowTodayDecisions() {
  return window['go']['main']['App']['GetWorkflowTodayDecisions']();
}

export function GetWorkflowTodayTasks() {
  return window['go']['main']['App']['GetWorkflowTodayTasks']();
}

export function GetXtQuantFolderPath() {
  return window['go']['main']['App']['GetXtQuantFolderPath']();
}

export function IsReady() {
  return window['go']['main']['App']['IsReady']();
}

export function ListActiveTasks() {
  return window['go']['main']['App']['ListActiveTasks']();
}

export function ListWorkflowTemplates() {
  return window['go']['main']['App']['ListWorkflowTemplates']();
}

export function LogLiveActivity(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LogLiveActivity'](arg1, arg2, arg3, arg4);
}

export function MonitorIntradayInvestmentPlan(arg1) {
  return window['go']['main']['App']['MonitorIntradayInvestmentPlan'](arg1);
}

export function PlaceTrade(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['PlaceTrade'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ProcessTradeablePool(arg1) {
  return window['go']['main']['App']['ProcessTradeablePool'](arg1);
}

export function PublishWorkflowEvent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PublishWorkflowEvent'](arg1, arg2, arg3, arg4);
}

export function RebuildInvestmentPlan(arg1) {
  return window['go']['main']['App']['RebuildInvestmentPlan'](arg1);
}

export function RecordDailySettlement(arg1) {
  return window['go']['main']['App']['RecordDailySettlement'](arg1);
}

export function RecordDailySnapshot() {
  return window['go']['main']['App']['RecordDailySnapshot']();
}

export function RecordOrderBookDaily(arg1) {
  return window['go']['main']['App']['RecordOrderBookDaily'](arg1);
}

export function RefreshPrices() {
  return window['go']['main']['App']['RefreshPrices']();
}

export function RefreshStrategyMetrics() {
  return window['go']['main']['App']['RefreshStrategyMetrics']();
}

export function RejectPlan(arg1, arg2) {
  return window['go']['main']['App']['RejectPlan'](arg1, arg2);
}

export function RejectStock(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RejectStock'](arg1, arg2, arg3, arg4);
}

export function ResetDefaults() {
  return window['go']['main']['App']['ResetDefaults']();
}

export function ResetPlanner() {
  return window['go']['main']['App']['ResetPlanner']();
}

export function ResetUserData(arg1) {
  return window['go']['main']['App']['ResetUserData'](arg1);
}

export function ResumeTrading() {
  return window['go']['main']['App']['ResumeTrading']();
}

export function RiskReviewDecision(arg1, arg2, arg3) {
  return window['go']['main']['App']['RiskReviewDecision'](arg1, arg2, arg3);
}

export function RunBacktest(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) {
  return window['go']['main']['App']['RunBacktest'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
}

export function RunCIODailyCheck() {
  return window['go']['main']['App']['RunCIODailyCheck']();
}

export function RunDailyCycle() {
  return window['go']['main']['App']['RunDailyCycle']();
}

export function RunManualWorkflow(arg1) {
  return window['go']['main']['App']['RunManualWorkflow'](arg1);
}

export function SaveProfileAnswers(arg1) {
  return window['go']['main']['App']['SaveProfileAnswers'](arg1);
}

export function ScreenStock(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ScreenStock'](arg1, arg2, arg3, arg4, arg5);
}

export function SetAISettings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetAISettings'](arg1, arg2, arg3, arg4);
}

export function SetActivityRefreshMinutes(arg1) {
  return window['go']['main']['App']['SetActivityRefreshMinutes'](arg1);
}

export function SetAuditRetentionDays(arg1) {
  return window['go']['main']['App']['SetAuditRetentionDays'](arg1);
}

export function SetBrokerConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetBrokerConfig'](arg1, arg2, arg3, arg4);
}

export function SetDataProvider(arg1) {
  return window['go']['main']['App']['SetDataProvider'](arg1);
}

export function SetInitialCapital(arg1) {
  return window['go']['main']['App']['SetInitialCapital'](arg1);
}

export function SetLLMLoggingEnabled(arg1) {
  return window['go']['main']['App']['SetLLMLoggingEnabled'](arg1);
}

export function SetMCPConfig(arg1, arg2) {
  return window['go']['main']['App']['SetMCPConfig'](arg1, arg2);
}

export function SetMarket(arg1) {
  return window['go']['main']['App']['SetMarket'](arg1);
}

export function SetQMTConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SetQMTConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SetTDXPath(arg1) {
  return window['go']['main']['App']['SetTDXPath'](arg1);
}

export function SetTradingMode(arg1) {
  return window['go']['main']['App']['SetTradingMode'](arg1);
}

export function StartAutoScheduler() {
  return window['go']['main']['App']['StartAutoScheduler']();
}

export function StartContinuousTrading() {
  return window['go']['main']['App']['StartContinuousTrading']();
}

export function StartDailyWorkflow() {
  return window['go']['main']['App']['StartDailyWorkflow']();
}

export function StartFinancialSync(arg1, arg2) {
  return window['go']['main']['App']['StartFinancialSync'](arg1, arg2);
}

export function StartGeneratePlan() {
  return window['go']['main']['App']['StartGeneratePlan']();
}

export function StartInterview(arg1) {
  return window['go']['main']['App']['StartInterview'](arg1);
}

export function StartStockSync(arg1) {
  return window['go']['main']['App']['StartStockSync'](arg1);
}

export function StartWorkflow(arg1) {
  return window['go']['main']['App']['StartWorkflow'](arg1);
}

export function StopAutoScheduler() {
  return window['go']['main']['App']['StopAutoScheduler']();
}

export function StopContinuousTrading() {
  return window['go']['main']['App']['StopContinuousTrading']();
}

export function SubmitScreenResult(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SubmitScreenResult'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function TestAIConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestAIConnection'](arg1, arg2, arg3, arg4);
}

export function TestDataProvider(arg1) {
  return window['go']['main']['App']['TestDataProvider'](arg1);
}

export function TestNativeTDX() {
  return window['go']['main']['App']['TestNativeTDX']();
}

export function TestQMTConnection() {
  return window['go']['main']['App']['TestQMTConnection']();
}

export function ToggleStrategyStatus(arg1) {
  return window['go']['main']['App']['ToggleStrategyStatus'](arg1);
}

export function TradeableStockQuickSubmit(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['TradeableStockQuickSubmit'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function TriggerDailyReview(arg1) {
  return window['go']['main']['App']['TriggerDailyReview'](arg1);
}

export function TriggerRebalance() {
  return window['go']['main']['App']['TriggerRebalance']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateStrategy(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdateStrategy'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpgradeTier(arg1) {
  return window['go']['main']['App']['UpgradeTier'](arg1);
}

export function ValidateCustomWeights(arg1) {
  return window['go']['main']['App']['ValidateCustomWeights'](arg1);
}

export function WindowIsMaximised() {
  return window['go']['main']['App']['WindowIsMaximised']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowQuit() {
  return window['go']['main']['App']['WindowQuit']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
