// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {llmstore} from '../models';
import {context} from '../models';

export function ApplyUpdate():Promise<void>;

export function ApproveDecisionByCIO(arg1:string):Promise<any>;

export function ApprovePlan(arg1:string,arg2:boolean):Promise<void>;

export function ApproveStock(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<any>;

export function ApproveWorkflow(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:string):Promise<any>;

export function BatchApproveStocks(arg1:string,arg2:string,arg3:string):Promise<any>;

export function BatchRejectStocks(arg1:string,arg2:string,arg3:string):Promise<any>;

export function BuyFromTradeablePool(arg1:string,arg2:number):Promise<any>;

export function CIOReviewPendingPlans():Promise<any>;

export function CIOReviewPlan(arg1:string):Promise<any>;

export function CalculateStructureRisk(arg1:Array<string>):Promise<any>;

export function CheckForUpdate():Promise<Record<string, any>>;

export function CheckLLMConnectivity():Promise<boolean>;

export function CleanupOldData():Promise<any>;

export function ClearAgentTaskLogs(arg1:string):Promise<any>;

export function ConfirmTradeApproval(arg1:string,arg2:boolean):Promise<void>;

export function ConnectNativeTDX():Promise<any>;

export function CreateInvestmentDecision(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:string):Promise<any>;

export function CreateStrategy(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number,arg7:number,arg8:string,arg9:string,arg10:Array<string>):Promise<any>;

export function DeleteBacktestResult(arg1:number):Promise<any>;

export function DeleteDailyReview(arg1:number):Promise<any>;

export function DeleteStrategy(arg1:number):Promise<any>;

export function DeleteTradeableStock(arg1:string):Promise<any>;

export function DownloadUpdate():Promise<void>;

export function EmergencyStop():Promise<void>;

export function ExecuteAllTasksManually():Promise<any>;

export function ExecuteDailyWorkflow():Promise<any>;

export function ExecuteManualTrade(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string):Promise<any>;

export function ExecutePhaseManually(arg1:string):Promise<any>;

export function ExecuteTaskManually(arg1:string):Promise<any>;

export function ExecuteWorkflow(arg1:string):Promise<any>;

export function FlushAuditLogs():Promise<any>;

export function ForceAuditCleanup():Promise<any>;

export function GenerateDailyReview():Promise<any>;

export function GenerateFactorHealthReport():Promise<any>;

export function GenerateMonthlyReport(arg1:number,arg2:number):Promise<any>;

export function GeneratePlan():Promise<any>;

export function GeneratePlanStockPool():Promise<any>;

export function GetAIStatus():Promise<any>;

export function GetActiveConversation():Promise<any>;

export function GetActiveWorkflows():Promise<any>;

export function GetAgentPermissions(arg1:string):Promise<any>;

export function GetAgentTaskLogs(arg1:string,arg2:string):Promise<any>;

export function GetAgentTaskLogsByDays(arg1:number):Promise<any>;

export function GetAgentTasks(arg1:string):Promise<any>;

export function GetAgentWorkDetails():Promise<any>;

export function GetAgentWorkbench(arg1:string):Promise<any>;

export function GetAllAgentTasks():Promise<any>;

export function GetAllAgentWorkbenches():Promise<any>;

export function GetAnnouncements(arg1:string,arg2:string,arg3:number):Promise<any>;

export function GetApprovedStocks():Promise<any>;

export function GetAuditEventTypes():Promise<any>;

export function GetAuditLogs(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<any>;

export function GetAuditRetentionDays():Promise<any>;

export function GetAuditServiceStats():Promise<any>;

export function GetAutoSchedulerStatus():Promise<any>;

export function GetBacktestResult(arg1:number):Promise<any>;

export function GetBacktestResults(arg1:string,arg2:string,arg3:number,arg4:number):Promise<any>;

export function GetBacktestStats():Promise<any>;

export function GetBoardList(arg1:string):Promise<any>;

export function GetBoardStocks(arg1:string):Promise<any>;

export function GetBuyableStocks():Promise<any>;

export function GetCIOJournal(arg1:number):Promise<any>;

export function GetCIOStatus():Promise<any>;

export function GetClaimAccuracy():Promise<any>;

export function GetConfig():Promise<any>;

export function GetContinuousTradingStatus():Promise<any>;

export function GetCurrentCycle():Promise<any>;

export function GetCurrentMarketState():Promise<any>;

export function GetCurrentPlan():Promise<any>;

export function GetDailyReviews(arg1:number):Promise<any>;

export function GetDailyStrategyPlans(arg1:number):Promise<any>;

export function GetETFMonitorData():Promise<any>;

export function GetETFMonitorKline(arg1:string):Promise<any>;

export function GetFinancialReportAsOf(arg1:string,arg2:string):Promise<any>;

export function GetFinancialSyncStatus():Promise<any>;

export function GetFundFlow(arg1:string,arg2:string):Promise<any>;

export function GetGeneratePlanProgress():Promise<any>;

export function GetIndexSnapshots(arg1:Array<string>):Promise<any>;

export function GetLLMCallLogs(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<llmstore.Entry>>;

export function GetLLMCallStats(arg1:string):Promise<Record<string, any>>;

export function GetLatestAgentTaskLogs():Promise<any>;

export function GetLatestDailyReview():Promise<any>;

export function GetLatestDailyStat():Promise<any>;

export function GetMarketDataStatus():Promise<any>;

export function GetMarketIndices():Promise<any>;

export function GetMarketPhaseInfo():Promise<any>;

export function GetMarketSixDimReports(arg1:number):Promise<any>;

export function GetOrchestratorStats():Promise<any>;

export function GetOrders(arg1:boolean):Promise<any>;

export function GetPendingStocks():Promise<any>;

export function GetPendingTradeApprovals():Promise<any>;

export function GetPendingWorkflows():Promise<any>;

export function GetPlan(arg1:string):Promise<any>;

export function GetPlannerState():Promise<any>;

export function GetPlans():Promise<any>;

export function GetPolicyStatus():Promise<any>;

export function GetPortfolioNavBenchmark(arg1:number):Promise<any>;

export function GetPortfolioRiskMetrics():Promise<any>;

export function GetPortfolioState():Promise<any>;

export function GetPositionSnapshots(arg1:string,arg2:string):Promise<any>;

export function GetPositions():Promise<any>;

export function GetProfile():Promise<any>;

export function GetProfitHistory(arg1:number):Promise<any>;

export function GetQMTConfig():Promise<any>;

export function GetStockSnapshots(arg1:Array<string>):Promise<any>;

export function GetStockSyncStatus():Promise<any>;

export function GetStrategies(arg1:string):Promise<any>;

export function GetStrategy(arg1:number):Promise<any>;

export function GetStrategyList():Promise<any>;

export function GetSystemHealth():Promise<any>;

export function GetSystemInfo():Promise<any>;

export function GetSystemStatus():Promise<any>;

export function GetTaskSchedulerStatus():Promise<any>;

export function GetTaskStatus(arg1:string):Promise<any>;

export function GetTaskStatusByRole():Promise<any>;

export function GetTeamActivity(arg1:number):Promise<any>;

export function GetTierInfo():Promise<any>;

export function GetTodayTeamActivity():Promise<any>;

export function GetTodayTrades():Promise<any>;

export function GetTradeHistory(arg1:number):Promise<any>;

export function GetTradeJSONFiles(arg1:number):Promise<any>;

export function GetTradeablePoolSummary():Promise<any>;

export function GetTradeableStockLogs(arg1:string):Promise<any>;

export function GetTradeableStocks(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<any>;

export function GetTradingMode():Promise<any>;

export function GetTransparencyData(arg1:string):Promise<any>;

export function GetTransparencyStats():Promise<any>;

export function GetUpdateStatus():Promise<Record<string, any>>;

export function GetUpgradePath():Promise<any>;

export function GetWatchList():Promise<any>;

export function GetWorkflowAgentTasks(arg1:string):Promise<any>;

export function GetWorkflowStats():Promise<any>;

export function GetWorkflowStatus(arg1:string):Promise<any>;

export function GetWorkflowSystemStatus():Promise<any>;

export function GetWorkflowTaskSummary():Promise<any>;

export function GetWorkflowTeamMembers():Promise<any>;

export function GetWorkflowTodayDecisions():Promise<any>;

export function GetWorkflowTodayTasks():Promise<any>;

export function GetXtQuantFolderPath():Promise<any>;

export function IsReady():Promise<Record<string, any>>;

export function ListActiveTasks():Promise<any>;

export function ListWorkflowTemplates():Promise<any>;

export function LogLiveActivity(arg1:string,arg2:string,arg3:string,arg4:string):Promise<any>;

export function MonitorIntradayInvestmentPlan(arg1:context.Context):Promise<void>;

export function PlaceTrade(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:string):Promise<any>;

export function ProcessTradeablePool(arg1:context.Context):Promise<void>;

export function PublishWorkflowEvent(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<any>;

export function RebuildInvestmentPlan(arg1:context.Context):Promise<void>;

export function RecordDailySettlement(arg1:context.Context):Promise<void>;

export function RecordDailySnapshot():Promise<any>;

export function RecordOrderBookDaily(arg1:context.Context):Promise<void>;

export function RefreshPrices():Promise<any>;

export function RefreshStrategyMetrics():Promise<any>;

export function RejectPlan(arg1:string,arg2:string):Promise<void>;

export function RejectStock(arg1:string,arg2:string,arg3:string,arg4:string):Promise<any>;

export function ResetDefaults():Promise<void>;

export function ResetPlanner():Promise<any>;

export function ResetUserData(arg1:string):Promise<any>;

export function ResumeTrading():Promise<void>;

export function RiskReviewDecision(arg1:string,arg2:boolean,arg3:string):Promise<any>;

export function RunBacktest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string,arg12:string):Promise<any>;

export function RunCIODailyCheck():Promise<any>;

export function RunDailyCycle():Promise<void>;

export function RunManualWorkflow(arg1:string):Promise<any>;

export function SaveProfileAnswers(arg1:Record<string, string>):Promise<void>;

export function ScreenStock(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string):Promise<any>;

export function SetAISettings(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetActivityRefreshMinutes(arg1:number):Promise<void>;

export function SetAuditRetentionDays(arg1:number):Promise<any>;

export function SetBrokerConfig(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetDataProvider(arg1:string):Promise<void>;

export function SetInitialCapital(arg1:number):Promise<void>;

export function SetLLMLoggingEnabled(arg1:boolean):Promise<void>;

export function SetMCPConfig(arg1:string,arg2:string):Promise<void>;

export function SetMarket(arg1:string):Promise<void>;

export function SetQMTConfig(arg1:boolean,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:string,arg7:string):Promise<void>;

export function SetTDXPath(arg1:string):Promise<void>;

export function SetTradingMode(arg1:string):Promise<void>;

export function StartAutoScheduler():Promise<void>;

export function StartContinuousTrading():Promise<void>;

export function StartDailyWorkflow():Promise<any>;

export function StartFinancialSync(arg1:string,arg2:string):Promise<any>;

export function StartGeneratePlan():Promise<any>;

export function StartInterview(arg1:string):Promise<any>;

export function StartStockSync(arg1:string):Promise<any>;

export function StartWorkflow(arg1:string):Promise<any>;

export function StopAutoScheduler():Promise<void>;

export function StopContinuousTrading():Promise<void>;

export function SubmitScreenResult(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string,arg6:string):Promise<any>;

export function TestAIConnection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<any>;

export function TestDataProvider(arg1:string):Promise<any>;

export function TestNativeTDX():Promise<any>;

export function TestQMTConnection():Promise<any>;

export function ToggleStrategyStatus(arg1:number):Promise<any>;

export function TradeableStockQuickSubmit(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:string,arg7:string):Promise<any>;

export function TriggerDailyReview(arg1:context.Context):Promise<void>;

export function TriggerRebalance():Promise<any>;

export function UpdateConfig(arg1:any):Promise<void>;

export function UpdateStrategy(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:number,arg8:number):Promise<any>;

export function UpdateTradingCalendar():Promise<any>;

export function UpgradeTier(arg1:string):Promise<void>;

export function ValidateCustomWeights(arg1:string):Promise<any>;

export function WindowIsMaximised():Promise<boolean>;

export function WindowMinimise():Promise<void>;

export function WindowQuit():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
